### ISSUE TITLE
powerUsage not always in toonstate

### ISSUE THREAD

**Issue by Erik1982** [rvdm/toon#3]
In get_power_usage, this line is used:

return self.toonstate["powerUsage"]

It seems like the power usage is not always returned, wich triggers this error:

 File "/home/pi/logging/Toon.py", line 75, in get_power_usage
    return self.toonstate["powerUsage"]
KeyError: 'powerUsage'

Same goes for gas usage

It seems to be rather random when the values are being returned or not. I first thought it wouldn't return anything when nothing had changed, but when my power consumption changed from 2000 watt to 600, it still did not return the powerUsage values upon the next call.

**Comment by bbredewold** [comment]
Skop

**Comment by rvdm** [comment]
The webapp doesn't enforce it; it just polls regularly, and updates only the values it gets. That works for something UI/javascript based, but not so much for a 'real' API consumer. I don't know why they do this, but realise toon is sending values back to eneco over 3G, so eneco not wanting to poll the toon itself on every API request might have something to do with it. I'll think about it, but PR's are welcome :)

**Comment by rvdm** [comment]
This should have been fixed by the last commit(s) - I'll close this issue. Feel free to re-open if your use case shows incomplete data.
