### ISSUE TITLE
Unable to read data

### ISSUE THREAD

**Issue by ferdyh** [rvdm/toon#6]
I'm trying to connect, however i'm faced by the following error:

Traceback (most recent call last):
  File "./toonclient.py", line 22, in <module>
    toon.login()
  File "/home/ferdy/toon/Toon.py", line 31, in login
    self.sessiondata = r.json()
TypeError: 'dict' object is not callable

**Comment by rvdm** [comment]
Can you give me a little more info on your environment? Python version? Requests module version? Are you, by chance, running Debian Stable? If you feel adventurous, try changing 'r.json()' on line 31 to 'r.json' and see if that helps.

**Comment by rvdm** [comment]
No responses on questions / many updates since the report was made. Closing; please re-open if the issue still exists (and add more info).
